### ISSUE TITLE
Is there a possibility to create a build without starting server?

### ISSUE THREAD

**Issue by xhujerr** [RodrigoGonzalez/check-mkdocs#43]
# Intro
I use [check-mkdocs](https://github.com/RodrigoGonzalez/check-mkdocs) in [pre-commit](https://pre-commit.com/). I want to actually generate the docs. So I use the the flag `--generate-build`.

# Current behavior
1. Starting the server takes a bit long to have it hooked to every commit. 
2. From some reason the server starts 3 times. (I don't know if there is some config option commanding how many times the server should start.)

# Desired behavior
1. I can build the documentation without starting the server. For example `--generate-build --no-server`
2. I can configure the number of attempts to start the server.

# More info
## My pre-commit entry:

```yaml
  - repo: https://github.com/RodrigoGonzalez/check-mkdocs
    rev: v1.2.0
    hooks:
      - id: check-mkdocs
        name: check-mkdocs
        args: ["--config", "mkdocs.yml", "--generate-build"]
        verbose: true
        additional_dependencies: ['mkdocs-material', 'mkdocs-awesome-pages-plugin', 'mkdocs-awesome-nav']
```
